language: php

php:
    - 7.2
    - 7.3
    - 7.4snapshot
    - nightly

matrix:
    fast_finish: true
    allow_failures:
        -   php: nightly

before_script:
    - composer install --prefer-dist -o

script:
    composer run ci
