language: php

php:
    - 8.0
    - 8.1

matrix:
    fast_finish: true
    allow_failures:
        -   php: nightly

install:
    - composer install --prefer-dist -o

script:
    composer run ci

jobs:
    include:
        - language: node_js
          node_js: 14
          install:
              - npm install
          script:
              - npm test
